/*
 * This Java source file was generated by the Gradle 'init' task.
 */
class App {
    private String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
